#!/bin/env sh

# --- Available Flags
betterc='F' # Use the `-betterC` flag.
libc='F'    # Use wasi-libc instead of the wasip1libc module.
test='F'    # Use the "examples/index_test.d" file.


set -eu
cd "$(dirname "$0")"
for arg in "$@"; do
    [ "$arg" = '-betterc' ] && betterc='T' && continue
    [ "$arg" = '-libc' ] && libc='T' && continue
    [ "$arg" = '-test' ] && test='T' && continue

    flag_count=4
    tail -n +3 "$0" | head -n $flag_count
    exit 1
done

dflags='-i --d-version=WASI_EMULATED_MMAN --d-version=WASI_EMULATED_SIGNAL'
[ "$betterc" = 'T' ] && dflags="$dflags -betterC"

if [ "$test" = 'T' ]; then
    echo 'Building test build.'
    ldc2 --mtriple=wasm32-wasip1 -c wasip1libc.d
    ldc2 --mtriple=wasm32-wasip1 -link-internally examples/index_test.d wasip1libc.o --of=index.wasm
elif [ "$libc" = 'T' ]; then
    ldc2 --mtriple=wasm32-wasip1 $dflags index.d
else
    ldc2 --mtriple=wasm32-wasip1 $dflags -c wasip1libc.d
    ldc2 --mtriple=wasm32-wasip1 $dflags -link-internally index.d wasip1libc.o
fi

rm -f *.o
